/* global Renderer */
window.Editor = (() => {
 const canvas=document.querySelector('#stage'), panel=document.querySelector('#panel'), picker=document.querySelector('#picker'), hint=document.querySelector('#hint');
 const layers=[0,1].map(()=>({image:null,mask:null,x:0,y:0,scale:1,rotation:0,opacity:1,lockScale:false,lockRotation:false,cuts:[],boundary:null,boundaryHistory:[]}));
 let selected=null, mode='normal', adding=null, pointers=new Map(), gesture=null, drag=null, stroke=null, boundaryDrag=null, lastTap=0;
 function resize(){const d=devicePixelRatio;canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';Renderer.render()} addEventListener('resize',resize);resize();
 function layer(){return selected===null?null:layers[selected]} function say(s){hint.textContent=s;hint.classList.remove('hidden');clearTimeout(say.t);say.t=setTimeout(()=>hint.classList.add('hidden'),1800)}
 function screenToLocal(l,x,y){const dx=x-l.x,dy=y-l.y,co=Math.cos(-l.rotation),si=Math.sin(-l.rotation);return{x:(dx*co-dy*si)/l.scale,y:(dx*si+dy*co)/l.scale}}
 function hit(l,x,y){if(!l.image)return false;const p=screenToLocal(l,x,y),w=l.image.naturalWidth/2,h=l.image.naturalHeight/2;return p.x>=-w&&p.x<=w&&p.y>=-h&&p.y<=h}
 function select(i){selected=i;mode='normal';sync();Renderer.render()}
 function sync(){document.querySelectorAll('[data-layer]').forEach(b=>b.classList.toggle('active',+b.dataset.layer===selected));const l=layer();['scale','rotation','opacity','lockScale','lockRotation'].forEach(id=>document.querySelector('#'+id).disabled=!l);if(!l)return;scale.value=Math.round(l.scale*100);rotation.value=Math.round(l.rotation*180/Math.PI);opacity.value=Math.round(l.opacity*100);lockScale.checked=l.lockScale;lockRotation.checked=l.lockRotation;scaleOut.value=scale.value+'%';rotationOut.value=rotation.value+'°';opacityOut.value=opacity.value+'%'}
 function setMode(m){mode=mode===m?'normal':m;document.querySelector('#cut').classList.toggle('active',mode==='cut');document.querySelector('#boundary').classList.toggle('active',mode==='boundary');document.querySelector('#segment').textContent='区間: '+(layer()?.boundary?.segments?.[0]==='line'?'直線':'曲線');say(mode==='cut'?'閉じた線を描くと内側を消去':'モードを切替') ;Renderer.render()}
 function cut(l,pts){if(pts.length<3)return; const before=l.mask?l.mask.getContext('2d').getImageData(0,0,l.mask.width,l.mask.height):null;l.cuts.push(before);if(!l.mask){l.mask=document.createElement('canvas');l.mask.width=l.image.naturalWidth;l.mask.height=l.image.naturalHeight}const c=l.mask.getContext('2d');c.globalCompositeOperation='source-over';c.fillStyle='#000';c.beginPath();c.moveTo(pts[0].x+l.image.naturalWidth/2,pts[0].y+l.image.naturalHeight/2);pts.slice(1).forEach(p=>c.lineTo(p.x+l.image.naturalWidth/2,p.y+l.image.naturalHeight/2));c.closePath();c.fill();mode='normal';document.querySelector('#cut').classList.remove('active');Renderer.render()}
 function undoCut(){const l=layer();if(!l||!l.cuts.length)return;const old=l.cuts.pop();if(!old){l.mask=null}else{if(!l.mask){l.mask=document.createElement('canvas');l.mask.width=l.image.naturalWidth;l.mask.height=l.image.naturalHeight}l.mask.getContext('2d').putImageData(old,0,0)}Renderer.render()}
 function boundarySave(l){l.boundaryHistory.push(l.boundary?JSON.parse(JSON.stringify(l.boundary)):null)}
 function simplify(a){return a.filter((p,i)=>i===0||i===a.length-1||Math.hypot(p.x-a[i-1].x,p.y-a[i-1].y)>10)}
 canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const l=layer();
  if(mode==='cut'&&l){stroke=[screenToLocal(l,e.clientX,e.clientY)];return}
  if(mode==='boundary'&&l){const p=screenToLocal(l,e.clientX,e.clientY);if(l.boundary){const i=l.boundary.points.findIndex(q=>Math.hypot(q.x-p.x,q.y-p.y)<18/l.scale);if(i>=0){boundarySave(l);boundaryDrag=i;return}}boundarySave(l);stroke=[p];return}
  if(pointers.size===1){const now=Date.now();if(now-lastTap<280){selected=null;sync();Renderer.render();lastTap=0;return}lastTap=now;let found=null;for(let i=1;i>=0;i--)if(hit(layers[i],e.clientX,e.clientY)){found=i;break}if(found===null){selected=null;sync();Renderer.render();return}select(found);drag={x:e.clientX,y:e.clientY,l:layers[found]}}
  else if(pointers.size===2&&l){const p=[...pointers.values()];gesture={distance:Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),angle:Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x),scale:l.scale,rotation:l.rotation}}
 });
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const l=layer();if(!l)return;
  if(stroke&&mode==='cut'){stroke.push(screenToLocal(l,e.clientX,e.clientY));Renderer.render();return}
  if(boundaryDrag!==null){l.boundary.points[boundaryDrag]=screenToLocal(l,e.clientX,e.clientY);Renderer.render();return}
  if(stroke&&mode==='boundary'){stroke.push(screenToLocal(l,e.clientX,e.clientY));Renderer.render();return}
  if(pointers.size===1&&drag){l.x+=e.clientX-drag.x;l.y+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;Renderer.render()}else if(pointers.size===2&&gesture){const p=[...pointers.values()],dist=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),ang=Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x);if(!l.lockScale)l.scale=Math.max(.1,Math.min(3,gesture.scale*dist/gesture.distance));if(!l.lockRotation)l.rotation=gesture.rotation+ang-gesture.angle;sync();Renderer.render()}
 });
 canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);const l=layer();if(stroke&&mode==='cut'){cut(l,stroke);stroke=null}else if(stroke&&mode==='boundary'){const pts=simplify(stroke);if(pts.length>1)l.boundary={points:pts,segments:Array(pts.length-1).fill('curve')};stroke=null;mode='normal';document.querySelector('#boundary').classList.remove('active');Renderer.render()}drag=null;boundaryDrag=null;gesture=null});canvas.addEventListener('pointercancel',()=>{pointers.clear();stroke=null;drag=null;gesture=null});
 document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>select(+b.dataset.layer));
 add.onclick=()=>{adding=selected===null?0:selected;picker.click()};picker.onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>{const l=layers[adding];l.image=im;l.mask=null;l.cuts=[];l.boundary=null;l.x=innerWidth/2;l.y=innerHeight/2;l.scale=Math.min(1,Math.min(innerWidth*.8/im.naturalWidth,innerHeight*.7/im.naturalHeight));l.rotation=0;l.opacity=1;select(adding);Renderer.render()};im.src=URL.createObjectURL(f);picker.value=''};
 adjust.onclick=()=>panel.classList.toggle('panel-open');cut.onclick=()=>layer()?setMode('cut'):say('先に画像を選択');undoCut.onclick=undoCut;save.onclick=Renderer.exportPNG;boundary.onclick=()=>layer()?setMode('boundary'):say('先に画像を選択');
 boundaryUndo.onclick=()=>{const l=layer();if(l&&l.boundaryHistory.length){l.boundary=l.boundaryHistory.pop();Renderer.render()}};boundaryDelete.onclick=()=>{const l=layer();if(l){boundarySave(l);l.boundary=null;Renderer.render()}};segment.onclick=()=>{const b=layer()?.boundary;if(!b)return;s=b.segments[0]==='curve'?'line':'curve';b.segments.fill(s);segment.textContent='区間: '+(s==='line'?'直線':'曲線');Renderer.render()};
 scale.oninput=()=>{if(layer()){layer().scale=+scale.value/100;scaleOut.value=scale.value+'%';Renderer.render()}};rotation.oninput=()=>{if(layer()){layer().rotation=+rotation.value*Math.PI/180;rotationOut.value=rotation.value+'°';Renderer.render()}};opacity.oninput=()=>{if(layer()){layer().opacity=+opacity.value/100;opacityOut.value=opacity.value+'%';Renderer.render()}};lockScale.onchange=()=>{if(layer())layer().lockScale=lockScale.checked};lockRotation.onchange=()=>{if(layer())layer().lockRotation=lockRotation.checked};
 if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
 return {canvas,layers,get selected(){return selected},get mode(){return mode}};
})();