/* global Renderer */
window.Editor = (() => {
  const $=s=>document.querySelector(s), canvas=$('#stage'), panel=$('#panel'), picker=$('#picker'), hint=$('#hint');
  const addButton=$('#add'),adjustButton=$('#adjust'),cutButton=$('#cut'),undoCutButton=$('#undoCut'),saveButton=$('#save');
  const boundaryButton=$('#boundary'),boundaryUndoButton=$('#boundaryUndo'),boundaryDeleteButton=$('#boundaryDelete'),segmentButton=$('#segment');
  const scaleSlider=$('#scale'),rotationSlider=$('#rotation'),opacitySlider=$('#opacity'),scaleOutput=$('#scaleOut'),rotationOutput=$('#rotationOut'),opacityOutput=$('#opacityOut'),lockScaleCheckbox=$('#lockScale'),lockRotationCheckbox=$('#lockRotation');
  const layers=[0,1].map(()=>({image:null,mask:null,x:0,y:0,scale:1,rotation:0,opacity:1,lockScale:false,lockRotation:false,cuts:[],boundary:null,boundaryHistory:[]}));
  const pointers=new Map(); let selected=null,mode='normal',adding=0,drag=null,gesture=null,stroke=null,boundaryDrag=null,lastTap=0,selectedSegment=0;
  function render(){Renderer.render()} function current(){return selected===null?null:layers[selected]}
  function resize(){const d=devicePixelRatio||1;canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';requestAnimationFrame(render)}
  function message(t){hint.textContent=t;hint.classList.remove('hidden');clearTimeout(message.timer);message.timer=setTimeout(()=>hint.classList.add('hidden'),1800)}
  function local(l,x,y){const dx=x-l.x,dy=y-l.y,c=Math.cos(-l.rotation),s=Math.sin(-l.rotation);return{x:(dx*c-dy*s)/l.scale,y:(dx*s+dy*c)/l.scale}}
  function contains(l,x,y){
    if(!l.image)return false; const p=local(l,x,y), w=l.image.naturalWidth/2,h=l.image.naturalHeight/2;
    if(Math.abs(p.x)>w||Math.abs(p.y)>h)return false;
    // カットマスクが不透明な箇所は、画像が存在しないものとして扱う。
    if(l.mask){const mx=Math.floor(p.x+w),my=Math.floor(p.y+h);if(mx>=0&&my>=0&&mx<l.mask.width&&my<l.mask.height&&l.mask.getContext('2d').getImageData(mx,my,1,1).data[3]>0)return false;}
    return true;
  }
  function sync(){document.querySelectorAll('[data-layer]').forEach(b=>b.classList.toggle('active',Number(b.dataset.layer)===selected));const l=current();[scaleSlider,rotationSlider,opacitySlider,lockScaleCheckbox,lockRotationCheckbox].forEach(e=>e.disabled=!l);if(!l)return;scaleSlider.value=Math.round(l.scale*100);rotationSlider.value=Math.round(l.rotation*180/Math.PI);opacitySlider.value=Math.round(l.opacity*100);scaleOutput.value=scaleSlider.value+'%';rotationOutput.value=rotationSlider.value+'°';opacityOutput.value=opacitySlider.value+'%';lockScaleCheckbox.checked=l.lockScale;lockRotationCheckbox.checked=l.lockRotation}
  function select(i){selected=i;mode='normal';updateMode();sync();render()}
  function updateMode(){cutButton.classList.toggle('active',mode==='cut');boundaryButton.classList.toggle('active',mode==='boundary');const b=current()?.boundary;if(b?.segments.length)segmentButton.textContent='区間: '+(b.segments[Math.min(selectedSegment,b.segments.length-1)]==='line'?'直線':'曲線')}
  function setMode(m){mode=mode===m?'normal':m;updateMode();render()}
  function saveBoundary(l){l.boundaryHistory.push(l.boundary?JSON.parse(JSON.stringify(l.boundary)):null)}
  function simplify(a){return a.filter((p,i)=>i===0||i===a.length-1||Math.hypot(p.x-a[i-1].x,p.y-a[i-1].y)>10)}
  function cut(l,points){if(points.length<3)return;l.cuts.push(l.mask?l.mask.getContext('2d').getImageData(0,0,l.mask.width,l.mask.height):null);if(!l.mask){l.mask=document.createElement('canvas');l.mask.width=l.image.naturalWidth;l.mask.height=l.image.naturalHeight}const c=l.mask.getContext('2d'),w=l.image.naturalWidth/2,h=l.image.naturalHeight/2;c.fillStyle='#000';c.beginPath();c.moveTo(points[0].x+w,points[0].y+h);points.slice(1).forEach(p=>c.lineTo(p.x+w,p.y+h));c.closePath();c.fill();mode='normal';updateMode();render()}
  function undoCut(){const l=current();if(!l?.cuts.length)return;const old=l.cuts.pop();if(!old)l.mask=null;else{if(!l.mask){l.mask=document.createElement('canvas');l.mask.width=l.image.naturalWidth;l.mask.height=l.image.naturalHeight}l.mask.getContext('2d').putImageData(old,0,0)}render()}
  canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const l=current();if(mode==='cut'&&l){stroke=[local(l,e.clientX,e.clientY)];render();return}if(mode==='boundary'&&l){const p=local(l,e.clientX,e.clientY),b=l.boundary;if(b){const i=b.points.findIndex(q=>Math.hypot(q.x-p.x,q.y-p.y)<18/l.scale);if(i>=0){saveBoundary(l);boundaryDrag=i;return}}saveBoundary(l);stroke=[p];return}if(pointers.size===1){const now=Date.now();if(now-lastTap<280){selected=null;lastTap=0;sync();render();return}lastTap=now;let found=null;for(let i=layers.length-1;i>=0;i--)if(contains(layers[i],e.clientX,e.clientY)){found=i;break}if(found===null){selected=null;sync();render();return}select(found);drag={x:e.clientX,y:e.clientY}}else if(pointers.size===2&&l){const p=[...pointers.values()];gesture={distance:Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),angle:Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x),scale:l.scale,rotation:l.rotation}}},{passive:false});
  canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const l=current();if(!l)return;if(stroke&&mode==='cut'){stroke.push(local(l,e.clientX,e.clientY));render();return}if(boundaryDrag!==null){l.boundary.points[boundaryDrag]=local(l,e.clientX,e.clientY);render();return}if(stroke&&mode==='boundary'){stroke.push(local(l,e.clientX,e.clientY));render();return}if(pointers.size===1&&drag){l.x+=e.clientX-drag.x;l.y+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;render()}else if(pointers.size===2&&gesture){const p=[...pointers.values()],d=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),a=Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x);if(!l.lockScale)l.scale=Math.max(.1,Math.min(3,gesture.scale*d/gesture.distance));if(!l.lockRotation)l.rotation=gesture.rotation+a-gesture.angle;sync();render()}},{passive:false});
  function end(e){pointers.delete(e.pointerId);const l=current();if(stroke&&mode==='cut'){const p=stroke;stroke=null;cut(l,p)}else if(stroke&&mode==='boundary'){const p=simplify(stroke);stroke=null;if(p.length>1)l.boundary={points:p,segments:Array(p.length-1).fill('curve')};mode='normal';updateMode();render()}drag=null;gesture=null;boundaryDrag=null}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
  document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>select(Number(b.dataset.layer)));addButton.onclick=()=>{adding=selected===null?0:selected;picker.click()};picker.onchange=e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.onload=()=>{const l=layers[adding];Object.assign(l,{image:img,mask:null,cuts:[],boundary:null,boundaryHistory:[],x:innerWidth/2,y:innerHeight/2,scale:Math.min(1,Math.min(innerWidth*.8/img.naturalWidth,innerHeight*.7/img.naturalHeight)),rotation:0,opacity:1});select(adding);URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(f);picker.value=''};
  adjustButton.onclick=()=>panel.classList.toggle('panel-open');cutButton.onclick=()=>current()?setMode('cut'):message('先に画像を選択');undoCutButton.onclick=undoCut;saveButton.onclick=Renderer.exportPNG;boundaryButton.onclick=()=>current()?setMode('boundary'):message('先に画像を選択');boundaryUndoButton.onclick=()=>{const l=current();if(l?.boundaryHistory.length){l.boundary=l.boundaryHistory.pop();render()}};boundaryDeleteButton.onclick=()=>{const l=current();if(l){saveBoundary(l);l.boundary=null;render()}};segmentButton.onclick=()=>{const b=current()?.boundary;if(!b?.segments.length)return;selectedSegment=Math.min(selectedSegment,b.segments.length-1);b.segments[selectedSegment]=b.segments[selectedSegment]==='curve'?'line':'curve';updateMode();render()};
  scaleSlider.oninput=()=>{const l=current();if(l){l.scale=Number(scaleSlider.value)/100;scaleOutput.value=scaleSlider.value+'%';render()}};rotationSlider.oninput=()=>{const l=current();if(l){l.rotation=Number(rotationSlider.value)*Math.PI/180;rotationOutput.value=rotationSlider.value+'°';render()}};opacitySlider.oninput=()=>{const l=current();if(l){l.opacity=Number(opacitySlider.value)/100;opacityOutput.value=opacitySlider.value+'%';render()}};lockScaleCheckbox.onchange=()=>{if(current())current().lockScale=lockScaleCheckbox.checked};lockRotationCheckbox.onchange=()=>{if(current())current().lockRotation=lockRotationCheckbox.checked};
  addEventListener('resize',resize);resize();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));return{canvas,layers,get selected(){return selected},get mode(){return mode},get cutPreview(){return stroke}};
})();